Repository amysiu1028/AeroBites, pull requests merged in 2024-01, with the labels that each got.

#21 feat/Add more fetches for terminals and business
  aerobites/src/AirportDetails/AirportDetail.js
  aerobites/src/Airports/Airports.js
  aerobites/src/ApiCalls/ApiCalls.js
  aerobites/src/App/App.js
  aerobites/src/index.js
Labels: enhancement

#24 Testing/favorite function
  aerobites/cypress/e2e/main_page.cy.js
  aerobites/cypress/fixtures/airportdata.json
  aerobites/cypress/fixtures/airports.json
  aerobites/src/AirportCard/AirportCard.js
  aerobites/src/AirportDetails/AirportDetail.js
  aerobites/src/FavoritedAirports/FavoritedAirports.js
Labels: testing

#26 fix/Delete test useEffect and clean up code
  aerobites/src/AirportCard/AirportCard.js
  aerobites/src/AirportDetails/AirportDetail.js
  aerobites/src/Airports/Airports.js
  aerobites/src/FavoritedAirports/FavoritedAirports.js
Labels: bug fix
